### ISSUE TITLE
Getting "TypeError: must be unicode, not str" when running for python

### ISSUE THREAD

**Issue by eoogbe** [googleapis/artman#214]
When running `artman --language python --api monitoring --publish noop` , I get
```
Traceback (most recent call last):
  File "/usr/local/google/home/eoogbe/googleapis/venv/bin/artman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/cli/main.py", line 86, in main
    engine.run()
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/tasks/python_grpc_tasks.py", line 78, in execute
    src_proto_path, new_proto_dir, common_protos, paths=new_src_path)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/tasks/python_grpc_tasks.py", line 147, in _copy_and_transform_directories
    proto, os.path.join(sub_new_src, dest), common_protos)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/tasks/python_grpc_tasks.py", line 125, in _copy_proto
    imprt.group('package'), '/', common_protos)))
TypeError: must be unicode, not str
```
This is different from [the error I get from running with ruby or php](https://github.com/googleapis/artman/issues/215).

**Comment by lukesneeringer** [comment]
I will see about fixing this. For now, make a Python 3 virtualenv and run Artman there. (We have shifted most of our testing to Python 3.)

**Comment by ethanbao** [comment]
Close this as we no longer seeing this.

**Comment by eoogbe** [comment]
Saw this today

**Comment by ethanbao** [comment]
@lukesneeringer What is the best practice to fix the issue like this?

**Comment by ethanbao** [comment]
Luke, can you advise a solution?

**Comment by vchudnov-g** [comment]
@lukesneeringer Update?

**Comment by vchudnov-g** [comment]
@lukesneeringer : Any updates (to stay in SLO)?

**Comment by noahdietz** [comment]
@lukesneeringer Any updates on this issue? Thanks!

**Comment by vchudnov-g** [comment]
@lukesneeringer Any updates on this?

We're out of SLO (>3mo since the last update)

**Comment by software-dov** [comment]
Closing as there has been no update for > 1 year.
