### ISSUE TITLE
Getting "OSError: [Errno 2] No such file or directory" when running for ruby

### ISSUE THREAD

**Issue by eoogbe** [googleapis/artman#215]
When running `artman --language ruby --api monitoring --publish noop` , I get
```
Traceback (most recent call last):
  File "/usr/local/google/home/eoogbe/googleapis/venv/bin/artman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/cli/main.py", line 86, in main
    engine.run()
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/tasks/protoc_tasks.py", line 157, in execute
    final_import_proto_path=final_import_proto_path)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/tasks/protoc_tasks.py", line 95, in _execute_proto_codegen
    protos)
  File "/usr/local/google/home/eoogbe/googleapis/venv/local/lib/python2.7/site-packages/artman/tasks/task_base.py", line 64, in exec_command
    output = subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Same happens when I run with `--publish=local` or `--lang=php`. When running with `--lang=python`, I get a [different error](https://github.com/googleapis/artman/issues/214).

**Comment by geigerj** [comment]
@ethanbao @lukesneeringer Could one of you take a look?

**Comment by lukesneeringer** [comment]
Fairly certain this has to do with not having artman within `reporoot`, which in theory we should stop requiring. I will look into fixing this.

**Comment by eoogbe** [comment]
Needed to install grpc-tools: `gem install grpc-tools --version '=1.0.0' --no-ri --no-rdoc`
