### ISSUE TITLE
artman2 assumes it is being run from googleapis directory

### ISSUE THREAD

**Issue by geigerj** [googleapis/artman#278]
### What

`artman2` seems to calculate paths to config assuming it is being run from the `googleapis` directory. It should calculate paths relative to the `--config` flag.

### Observed behavior

```
jgeiger@jgeiger:~/repos/gapi-dev/artman$ artman2 --config ../googleapis/gapic/api/artman_speech_v1.yaml --output-dir output/ generate ruby_gapic
Traceback (most recent call last):
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/.nox/unit_tests-python_version-3-5/bin/artman2", line 11, in <module>
    load_entry_point('googleapis-artman', 'console_scripts', 'artman2')()
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/artman/cli/main2.py", line 58, in main
    pipeline_name, pipeline_kwargs = normalize_flags(flags, user_config)
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/artman/cli/main2.py", line 347, in normalize_flags
    language=language, )
  File "/usr/local/google/home/jgeiger/repos/gapi-dev/artman/artman/utils/config_util.py", line 30, in load_config_spec
    with open(config_path) as config_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/google/home/jgeiger/repos/gapi-dev/artman/gapic/lang/doc.yaml'
```

**Comment by lukesneeringer** [comment]
Mostly fixed by #274.

There is a nitpick annoyance left where if you are running artman in Docker, it still dumps the _output_ to your googleapis directory.
