### ISSUE TITLE
IOError: No such file or directory on Windows

### ISSUE THREAD

**Issue by will-hart** [googleapis/artman#307]
When running `artman` and `artman2`  on Windows with the following command:

    D:\Code\artman> artman --config googleapis/google/firestore/artman_firestore.yaml generate csharp_gapic

I get the following error:

    Traceback (most recent call last):
      File "c:\users\will\anaconda\Lib\runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "c:\users\will\anaconda\Lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Users\Will\Envs\artman\Scripts\artman.exe\__main__.py", line 9, in <module>
      File "c:\users\will\envs\artman\lib\site-packages\artman\cli\main.py", line 58, in main
        pipeline_name, pipeline_kwargs = normalize_flags(flags, user_config)
      File "c:\users\will\envs\artman\lib\site-packages\artman\cli\main.py", line 365, in normalize_flags
        language=language, )
      File "c:\users\will\envs\artman\lib\site-packages\artman\utils\config_util.py", line 30, in     load_config_spec
        with open(config_path) as config_file:
    IOError: [Errno 2] No such file or directory: 'D'

My `config.yaml` looks like this:

    ---
    local_paths:
      api_client_staging: D:/Code/artman/api-client-staging
      googleapis: D:/Code/artman/googleapis
      reporoot: D:/Code
      toolkit: D:/Code/artman/toolkit
    publish: local

I'm running `Windows 10 16299.19` and I've tried in `cmd` and `powershell` and get the same error.

**Comment by ethanbao** [comment]
Artman is intended to work on Windows, but some code currently is *nix specific. I am going to fix that.

**Comment by vchudnov-g** [comment]
@lukesneeringer Update? (It's OK to deprioritize this given the upcoming move away from artman)

**Comment by vchudnov-g** [comment]
Dropping to P3 since we're moving away from artman

**Comment by vchudnov-g** [comment]
We are deprecating the use of artman, so this may not get fixed. @vam-google , please feel free to chime in.

**Comment by vam-google** [comment]
@Yes, this should be closed. Artman is currently used only for portion of ruby clients and that is it.
