### ISSUE TITLE
artman fails to generate java_grpc for google-common-protos

### ISSUE THREAD

**Issue by andreamlin** [googleapis/artman#445]
Running the command 
```
$ artman         --config=google/artman_core.yaml  --local generate java_grpc
```

Results in the following output:

```
artman> Final args:
artman>   api_name: !!python/unicode 'common-protos'
artman>   api_version: !!python/unicode ''
artman>   artifact_type: GRPC
artman>   desc_proto_path: []
artman>   excluded_proto_path:
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/api/servicemanagement'
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/api/servicecontrol'
artman>   gapic_code_dir: !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/artman-genfiles/java/gapic-google-cloud-common-protos-'
artman>   gapic_yaml: !!python/unicode ''
artman>   git_repos:
artman>     !!python/unicode 'staging':
artman>       location: !!python/unicode 'git@github.com:googleapis/api-client-staging.git'
artman>       paths:
artman>         - artifact: !!python/unicode 'grpc'
artman>         dest: !!python/unicode 'generated/java/grpc-google-common-protos'
artman>         - artifact: !!python/unicode 'proto'
artman>         dest: !!python/unicode 'generated/java/proto-google-common-protos'
artman>   import_proto_path:
artman>     - /usr/local/google/home/andrealin/Documents/git/veneer/googleapis
artman>   language: java
artman>   organization_name: !!python/unicode 'google'
artman>   output_dir: /usr/local/google/home/andrealin/Documents/git/veneer/googleapis/artman-genfiles
artman>   proto_deps: []
artman>   proto_test_deps: []
artman>   publish: noop
artman>   release_level: ga
artman>   root_dir: /usr/local/google/home/andrealin/Documents/git/veneer/googleapis
artman>   service_yaml: !!python/unicode ''
artman>   src_proto_path:
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/api'
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/cloud/audit'
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/logging/type'
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/longrunning'
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/rpc'
artman>     - !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/google/type'
artman>   toolkit: !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/toolkit'
artman>   toolkit_path: !!python/unicode '/usr/local/google/home/andrealin/Documents/git/veneer/toolkit'
artman>   
artman> Creating GrpcClientPipeline.
artman.output >
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:211)
	at com.google.api.tools.framework.tools.ToolUtil.sanitizeSourceFiles(ToolUtil.java:169)
	at com.google.api.tools.framework.tools.ModelBuilder.parseConfigFiles(ModelBuilder.java:159)
	at com.google.api.tools.framework.tools.ModelBuilder.setup(ModelBuilder.java:48)
	at com.google.api.tools.framework.tools.ToolDriverBase.setupModel(ToolDriverBase.java:81)
	at com.google.api.tools.framework.tools.ToolDriverBase.run(ToolDriverBase.java:72)
	at com.google.api.codegen.GeneratorMain.packageGeneratorMain(GeneratorMain.java:313)
	at com.google.api.codegen.GeneratorMain.main(GeneratorMain.java:156)

artman> Traceback (most recent call last):
  File "/usr/local/google/home/andrealin/Documents/git/veneer/artman/artman/cli/main.py", line 71, in main
    engine.run()
  File "/opt/virtual_env/artman3/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/opt/virtual_env/artman3/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/opt/virtual_env/artman3/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/opt/virtual_env/artman3/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/opt/virtual_env/artman3/local/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/usr/local/google/home/andrealin/Documents/git/veneer/artman/artman/tasks/package_metadata_tasks.py", line 119, in execute
    language, 'PROTOBUF')
  File "/usr/local/google/home/andrealin/Documents/git/veneer/artman/artman/tasks/package_metadata_tasks.py", line 101, in _execute
    task_utils.gapic_gen_task(toolkit_path, ['LEGACY_GRPC_PACKAGE'] + args))
  File "/usr/local/google/home/andrealin/Documents/git/veneer/artman/artman/tasks/task_base.py", line 64, in exec_command
    raise e
CalledProcessError: Command '['java', '-cp', u'/usr/local/google/home/andrealin/Documents/git/veneer/toolkit/build/libs/gapic-generator-latest-fatjar.jar', 'com.google.api.codegen.GeneratorMain', 'LEGACY_GRPC_PACKAGE', u'--descriptor_set=/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/artman-genfiles/google-common-protos.desc', u'--input=/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/artman-genfiles/java/proto-google-common-protos', u'--output=/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/artman-genfiles/java/proto-google-common-protos', u'--package_yaml2=/usr/local/google/home/andrealin/Documents/git/veneer/googleapis/artman-genfiles/java_google-common-protos_package2.yaml', '--artifact_type=PROTOBUF', '--language=java', u'--service_yaml=/usr/local/google/home/andrealin/Documents/git/veneer/googleapis']' returned non-zero exit status 1
```

The current workaround is the ctrl-c the process before gapic-generator is invoked; this ensures that artman's generated descriptor set is created but doesn't get erased. Then, run the gapic-generator GeneratorMain class with the `LEGACY_GRPC_PACKAGE` target and the same param values for `--descriptor_set`, `--input`, `--package_yaml2`, `--artifact_type`, `--language`, `--output` from the error message.

**Comment by andreamlin** [comment]
Setting as P2 because google-common-protos isn't generated that often, and there is a workaround.

**Comment by garrettjonesgoogle** [comment]
I ran this locally for myself, and it didn't fail...

**Comment by andreamlin** [comment]
It works for me locally now too.
