### ISSUE TITLE
python and ruby generation of artman_containeranalysis_v1beta1 fails

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/artman#483]
The recent [addition](https://github.com/googleapis/googleapis/compare/201d7be7f9da...8dfde277c731) of [artman_containeranalysis_v1beta1.yaml](https://github.com/googleapis/googleapis/blob/master/google/devtools/containeranalysis/artman_containeranalysis_v1beta1.yaml) breaks googleapis CI ([failure](https://circleci.com/gh/googleapis/googleapis/1316)): Python and Ruby generation fails.

```
Failure:
Failed to generate python_gapic of /var/code/googleapis/google/devtools/containeranalysis/artman_containeranalysis_v1beta1.yaml.
Failed to generate ruby_gapic of /var/code/googleapis/google/devtools/containeranalysis/artman_containeranalysis_v1beta1.yaml.
```

It might be either Artman error or the configuration failure. @jbolinger, @lukesneeringer: can you guys please take a look if it's something we should fix, or whitelist the failures?

**Comment by alexander-fenster** [comment]
I can reproduce the Python failure locally, but I don't really understand for now which file it cannot find.

```
$ ~/.local/bin/artman --local --verbose --config ./google/devtools/containeranalysis/artman_containeranalysis_v1beta1.yaml generate python_gapic
artman> Below is the legacy config after conversion:
{'common': {'api_name': u'containeranalysis',
            'api_version': u'v1beta1',
            'artifact_type': 'GAPIC',
            'gapic_yaml': u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml',
            'import_proto_path': ['/usr/local/google/home/fenster/googleapis'],
            'organization_name': u'google-cloud',
            'output_dir': '/usr/local/google/home/fenster/googleapis/artman-genfiles',
            'proto_deps': [{'name': u'google-common-protos'},
                           {'name': u'google-iam-v1'}],
            'service_yaml': u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/containeranalysis_v1beta1.yaml',
            'src_proto_path': [u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1']},
 'python': {'gapic_code_dir': u'/usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1',
            'git_repos': {}}}
artman> Final args:
artman>   api_name: !!python/unicode 'containeranalysis'
artman>   api_version: !!python/unicode 'v1beta1'
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: !!python/unicode '/usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1'
artman>   gapic_yaml: !!python/unicode '/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml'
artman>   git_repos: {}
artman>   import_proto_path:
artman>     - /usr/local/google/home/fenster/googleapis
artman>   language: python
artman>   organization_name: !!python/unicode 'google-cloud'
artman>   output_dir: /usr/local/google/home/fenster/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: !!python/unicode 'google-common-protos'
artman>     - name: !!python/unicode 'google-iam-v1'
artman>   publish: noop
artman>   root_dir: /usr/local/google/home/fenster/googleapis
artman>   service_yaml: !!python/unicode '/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/containeranalysis_v1beta1.yaml'
artman>   src_proto_path:
artman>     - !!python/unicode '/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1'
artman>   toolkit_path: !!python/unicode '/usr/local/google/home/fenster/gapic-generator'
artman>   
artman> Creating GapicClientPipeline.
taskflow.engines.helpers> Looking for 'serial' engine driver in 'taskflow.engines'
stevedore.extension> found extension EntryPoint.parse('default = taskflow.engines.action_engine.engine:SerialActionEngine')
stevedore.extension> found extension EntryPoint.parse('serial = taskflow.engines.action_engine.engine:SerialActionEngine')
stevedore.extension> found extension EntryPoint.parse('workers = taskflow.engines.worker_based.engine:WorkerBasedActionEngine')
stevedore.extension> found extension EntryPoint.parse('worker-based = taskflow.engines.worker_based.engine:WorkerBasedActionEngine')
stevedore.extension> found extension EntryPoint.parse('parallel = taskflow.engines.action_engine.engine:ParallelActionEngine')
artman> Compiling descriptors for [u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/grafeas/grafeas.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/vulnerability/vulnerability.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/deployment/deployment.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/discovery/discovery.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/attestation/attestation.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/package/package.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/image/image.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/common/common.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/source/source.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/build/build.proto', u'/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/provenance/provenance.proto']
artman> mkdir -p /usr/local/google/home/fenster/googleapis/artman-genfiles
artman> Searching for latest protobuf source
artman> protoc --proto_path=/usr/local/google/home/fenster/googleapis --proto_path=/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1 --proto_path=/usr/local/google/home/fenster/gapic-generator/build/toolpaths/protobufJavaDir --include_imports --include_source_info -o /usr/local/google/home/fenster/googleapis/artman-genfiles/google-cloud-containeranalysis-v1beta1.desc /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/grafeas/grafeas.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/vulnerability/vulnerability.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/deployment/deployment.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/discovery/discovery.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/attestation/attestation.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/package/package.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/image/image.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/common/common.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/source/source.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/build/build.proto /usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/provenance/provenance.proto
artman> rm -r /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/setup.cfg /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/google /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/MANIFEST.in /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/setup.py /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/LICENSE /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/tests /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/docs /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/README.rst /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1/nox.py
artman> java -cp /usr/local/google/home/fenster/gapic-generator/build/libs/gapic-generator-latest-fatjar.jar com.google.api.codegen.GeneratorMain LEGACY_GAPIC_AND_PACKAGE --descriptor_set=/usr/local/google/home/fenster/googleapis/artman-genfiles/google-cloud-containeranalysis-v1beta1.desc --package_yaml2=/usr/local/google/home/fenster/googleapis/artman-genfiles/python_google-cloud-containeranalysis-v1beta1_package2.yaml --output=/usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1 --language=python --service_yaml=/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/containeranalysis_v1beta1.yaml --gapic_yaml=/usr/local/google/home/fenster/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml
artman.output >
WARNING: toplevel: (lint) control-presence: Service containeranalysis.googleapis.com does not have control environment configured.

artman> Formatting files in /usr/local/google/home/fenster/googleapis/artman-genfiles/python/containeranalysis-v1beta1.
taskflow.engines.action_engine.completer> Applying resolver 'RevertAll(strategy=REVERT_ALL)' to resolve failure 'Failure: OSError: [Errno 2] No such file or directory' of atom 'PythonFormatTask-python-containeranalysis-v1beta1==1.0'
taskflow.engines.action_engine.completer> Modified/tweaked 9 nodes while applying resolver 'RevertAll(strategy=REVERT_ALL)'
taskflow.engines.action_engine.builder> Discarding failure 'Failure: OSError: [Errno 2] No such file or directory' (in response to outcome 'executed') under completion units request during completion of atom 'PythonFormatTask-python-containeranalysis-v1beta1==1.0' (intention is to REVERT)
artman> Traceback (most recent call last):
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/artman/cli/main.py", line 71, in main
    engine.run()
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/usr/local/google/home/fenster/.local/venvs/googleapis-artman/local/lib/python2.7/site-packages/artman/tasks/format_tasks.py", line 56, in execute
    exit_code = subprocess.call(['yapf', '-i'] + targetFiles)
  File "/usr/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by jbolinger** [comment]
I think this is failing because the proto service has a version suffix. In the v1beta1 proto file it is defined as:

```
service ContainerAnalysisV1Beta1 { ... }
```

In the v1apha1 proto file it is defined as:

```
service ContainerAnalysis { ... }
```

I suspect that the service should not have a version suffix on it?

**Comment by vtsao** [comment]
We need the suffix to serve both versions of the API from the same binary.

**Comment by jbolinger** [comment]
Sure, but does the service name need the suffix to enable that? Can't it just be in the package name?

**Comment by vtsao** [comment]
Having two services named the same but different packages doesn't work with ESF so we had to do this suffix.

**Comment by jbolinger** [comment]
The Ruby generator doesn't currently support that. I've opened an issue for it here: https://github.com/googleapis/gapic-generator/issues/2192.

Are you concerned about the names in the libraries as a result? I just generated the Java library to see what this would look like and classes like `com.google.cloud.devtools.containeranalysis.v1beta1.ContainerAnalysisV1Beta1Client` look a bit odd to me. 

If you could name the service differently, but not have it look like a version number, then I think it would work for Ruby and the name might look less odd. Is that an option?

**Comment by andreamlin** [comment]
Whenever this gets fixed, would someone mind removing the no-longer-failing configs from the smoketest file? i.e. revert https://github.com/googleapis/artman/pull/484

**Comment by lukesneeringer** [comment]
> Having two services named the same but different packages doesn't work with ESF so we had to do this suffix.

People do this all the time.

**Comment by lukesneeringer** [comment]
Incidentally, I am looking into fixing this in Python. Regardless of whether it is advisable, it should not crash our infra. :-)

**Comment by lukesneeringer** [comment]
Update on this: It works in gapic-generator-python. I have no idea why it does not work in gapic-generator though.

**Comment by vchudnov-g** [comment]
@lukesneeringer @jbolinger Any updates (to stay in SLO)?

**Comment by jbolinger** [comment]
I made a change some time ago that may have fixed this issue in Ruby. Have these tests been run recently?

**Comment by busunkim96** [comment]
@lukesneeringer @jbolinger It looks like this has been resolved for Ruby https://circleci.com/gh/googleapis/googleapis/1545. Are there any updates for Python?

**Comment by vchudnov-g** [comment]
Any updates on this? We're out of SLO (>3mo since last update)

**Comment by software-dov** [comment]
Tentatively closing issue due to lack of response.
