### ISSUE TITLE
artman fails to parse containeranalysis

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#489]
When I try to run artman against `google/devtools/containeranalysis/artman_containeranalysis_v1beta1.yaml`, I get:

```
ERROR: containeranalysis_gapic.yaml:11: Parsing of field 'release_level' failed: Failed to parse text 'beta' for proto field 'com.google.api.codegen.LanguageSettingsProto.release_level' of type 'ENUM' for reason: Enum type 'com.google.api.codegen.ReleaseLevel' has no value with name 'beta'
```

Expanded error:

```
artman> Running artman command in a Docker instance.
artman> artman> Final args:
artman>   api_name: containeranalysis
artman>   api_version: v1beta1
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-containeranalysis-go
artman>   gapic_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml
artman>   import_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   language: go
artman>   organization_name: google-cloud
artman>   output_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>     - name: google-iam-v1
artman>   root_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   service_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/devtools/containeranalysis/containeranalysis_v1beta1.yaml
artman>   src_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/devtools/containeranalysis/v1beta1
artman>   toolkit_path: /toolkit
artman>
artman> Creating GapicClientPipeline.
artman.output >
ERROR: containeranalysis_gapic.yaml:11: Parsing of field 'release_level' failed: Failed to parse text 'beta' for proto field 'com.google.api.codegen.LanguageSettingsProto.release_level' of type 'ENUM' for reason: Enum type 'com.google.api.codegen.ReleaseLevel' has no value with name 'beta'

artman> Traceback (most recent call last):
  File "/artman/artman/cli/main.py", line 71, in main
    engine.run()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/artman/artman/tasks/gapic_tasks.py", line 132, in execute
    task_utils.gapic_gen_task(toolkit_path, [gapic_artifact] + args))
  File "/artman/artman/tasks/task_base.py", line 64, in exec_command
    raise e
  File "/artman/artman/tasks/task_base.py", line 56, in exec_command
    output = subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-cp', '/toolkit/build/libs/gapic-generator-latest-fatjar.jar', 'com.google.api.codegen.GeneratorMain', 'LEGACY_GAPIC_AND_PACKAGE', '--descriptor_set=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/google-cloud-containeranalysis-v1beta1.desc', '--package_yaml2=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/go_google-cloud-containeranalysis-v1beta1_package2.yaml', '--output=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-containeranalysis-go', '--language=go', '--service_yaml=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/devtools/containeranalysis/containeranalysis_v1beta1.yaml', '--gapic_yaml=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml']' returned non-zero exit status 1


artman> Artman execution failed. For additional logging, re-run the command with the "--verbose" flag
```

**Comment by alexander-fenster** [comment]
Is it a dup of #483?

**Comment by jbolinger** [comment]
I doubt it, I think it just needs to be `BETA` instead of `beta`.

**Comment by jadekler** [comment]
Thanks!
