### ISSUE TITLE
Installation is failed with `pipsi`

### ISSUE THREAD

**Issue by realityone** [googleapis/artman#507]
Hi, 

I'm trying to install artman with `pipsi`.
I clone the code and run `pipsi install .` within directory. But failed with these logs:

```
[realityone@rEimu ~/Softs/artman]$ pipsi install .
Traceback (most recent call last):
  File "/Users/realityone/.local/bin/pipsi", line 11, in <module>
    sys.exit(cli())
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pipsi.py", line 366, in install
    if repo.install(package, python, editable):
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pipsi.py", line 215, in install
    venv_path = self.get_package_path(package)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pipsi.py", line 187, in get_package_path
    return join(self.home, normalize_package(package))
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pipsi.py", line 61, in normalize_package
    requirement = Requirement.parse(value)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3009, in parse
    req, = parse_requirements(s)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2956, in parse_requirements
    yield Requirement(line)
  File "/Users/realityone/.local/venvs/pipsi/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2965, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "': 0.15.7'"
```

After digging into the `setup.py` file, I found we should remove the 

```
print('Version: %s' % current_version)
```

line, otherwise `pipsi` will failed to parse requirements.

Is this add by mistake or this is by designed.

Any help will be appreciated.

**Comment by alexander-fenster** [comment]
Hello @realityone,

You're right, looks like `pipsi install .` is broken. I'm fixing it in #512 and will release the new version when it's merged. Until then, you can just remove that `print` from `setup.py`.

Thanks!
