### ISSUE TITLE
pip install artman fails

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#511]
```
$ pip install googleapis-artman
Collecting googleapis-artman
  Using cached https://files.pythonhosted.org/packages/8c/18/d58e5ceb61f4f24ed883d94ae88d1e8e151ca2998790c594bacbf68e4df0/googleapis-artman-0.15.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lk/zs4m7sv12mq2vzk_wfn2tfvm00h16k/T/pip-install-nwepd2xm/googleapis-artman/setup.py", line 29, in <module>
        with io.open(os.path.join(cur_dir, 'Dockerfile')) as dockerfile:
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/lk/zs4m7sv12mq2vzk_wfn2tfvm00h16k/T/pip-install-nwepd2xm/googleapis-artman/Dockerfile'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lk/zs4m7sv12mq2vzk_wfn2tfvm00h16k/T/pip-install-nwepd2xm/googleapis-artman/
```

**Comment by jadekler** [comment]
Ditto 0.15.6. Works fine for 0.15.5.

**Comment by alexander-fenster** [comment]
Taken care of in #509 and now releasing 0.15.8 in #510.
