### ISSUE TITLE
Generating python gapic for iamcredentials fails

### ISSUE THREAD

**Issue by hzyi-google** [googleapis/artman#518]
Command:

`
subprocess.CalledProcessError: Command '['docker', 'run', '--name', 'artman-docker', '--rm', '-i', '-e', 'HOST_USER_ID=545121', '-e', 'HOST_GROUP_ID=89939', '-e', 'RUNNING_IN_ARTMAN_DOCKER=True', '-v', '/Users/crwilcox/.cache/synthtool/googleapis:/Users/crwilcox/.cache/synthtool/googleapis', '-v', '/Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles:/Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles', '-w', PosixPath('/Users/crwilcox/.cache/synthtool/googleapis'), 'googleapis/artman:latest', '/bin/bash', '-c', 'artman --local --config google/iam/credentials/artman_iamcredentials_v1.yaml generate python_gapic']' returned non-zero exit status 32.
`

Error:
```
ynthtool > Failed executing docker run --name artman-docker --rm -i -e HOST_USER_ID=545121 -e HOST_GROUP_ID=89939 -e RUNNING_IN_ARTMAN_DOCKER=True -v /Users/crwilcox/.cache/synthtool/googleapis:/Users/crwilcox/.cache/synthtool/googleapis -v /Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles:/Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles -w /Users/crwilcox/.cache/synthtool/googleapis googleapis/artman:latest /bin/bash -c artman --local --config google/iam/credentials/artman_iamcredentials_v1.yaml generate python_gapic:

artman> Final args:
artman> api_name: iamcredentials
artman> api_version: v1
artman> artifact_type: GAPIC
artman> aspect: ALL
artman> gapic_code_dir: /Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles/python/iamcredentials-v1
artman> gapic_yaml: /Users/crwilcox/.cache/synthtool/googleapis/google/iam/credentials/v1/iamcredentials_gapic.yaml
artman> import_proto_path:
artman> - /Users/crwilcox/.cache/synthtool/googleapis
artman> language: python
artman> organization_name: google-cloud
artman> output_dir: /Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles
artman> proto_deps:
artman> - name: google-common-protos
artman> root_dir: /Users/crwilcox/.cache/synthtool/googleapis
artman> service_yaml: /Users/crwilcox/.cache/synthtool/googleapis/google/iam/credentials/iamcredentials_v1.yaml
artman> src_proto_path:
artman> - /Users/crwilcox/.cache/synthtool/googleapis/google/iam/credentials/v1
artman> toolkit_path: /toolkit
artman>
artman> Creating GapicClientPipeline.
artman> Traceback (most recent call last):
File "/artman/artman/cli/main.py", line 71, in main
engine.run()
File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 160, in run
pass
File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
self.gen.throw(type, value, traceback)
File "/usr/local/lib/python3.5/dist-packages/fasteners/lock.py", line 264, in try_lock
yield was_locked
File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 159, in run
for _state in self.run_iter():
File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
failure.Failure.reraise_if_any(it)
File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
self.gen.throw(type, value, traceback)
File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 52, in _start_stop
yield (task_executor, retry_executor)
File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
failure.Failure.reraise_if_any(it)
File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 292, in reraise_if_any
failures[0].reraise()
File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 299, in reraise
six.reraise(*self._exc_info)
File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
raise value
File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
result = task.execute(**arguments)
File "/artman/artman/tasks/python_grpc_tasks.py", line 197, in execute
src = self._get_subdir_path(grpc_code_dir, 'proto')
File "/artman/artman/tasks/python_grpc_tasks.py", line 237, in _get_subdir_path
raise RuntimeError('Path %s not found in %s.' % (needle, haystack))
RuntimeError: Path proto not found in /Users/crwilcox/.cache/synthtool/googleapis/artman-genfiles/python/grpc-google-cloud-iamcredentials-v1.
```

**Comment by hzyi-google** [comment]
I think I found the issue. `iamcredentials` is in the common-protos so the generated protos would not be put in a directory named `proto` as per [here](https://github.com/googleapis/artman/blob/d33d2d5c9b7d7d4b5024924cf80b17770d86cc03/artman/tasks/python_grpc_tasks.py#L116). Therefore the error is raised [here](https://github.com/googleapis/artman/blob/d33d2d5c9b7d7d4b5024924cf80b17770d86cc03/artman/tasks/python_grpc_tasks.py#L237). I'll have a fix soon. cc/ @crwilcox
