### ISSUE TITLE
Missing input file. should be more descriptive

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#544]
Sometimes artman fails with, `Missing input file.`. It would be really nice if it said, `Missing input file /foo/bar/gaz.txt.` :)

**Comment by andreamlin** [comment]
@jadekler Would you mind printing out a sample stack trace? I'm trying to grep for `"Missing input file"` and variants of that but nothing is coming up, so I'm guessing it's some I/O dependency that's throwing that?

**Comment by jadekler** [comment]
Certainly!

```
[...]
artman>   toolkit_path: /toolkit
artman>
artman> Creating GapicClientPipeline.
artman> Code generated: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-language-go
artman> GRPC code generated: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/go/grpc-google-cloud-language-v1

+ cp -r artman-genfiles/gapi-cloud-language-go/cloud.google.com/go/language /Users/deklerk/workspace/go/src/cloud.google.com/go/
+ for api in '"${APIS[@]}"'
+ rm -rf artman-genfiles/gapi-cloud-language-go artman-genfiles/go artman-genfiles/go_google-cloud-language-v1_package2.yaml artman-genfiles/google-cloud-language-v1.desc
+ artman --config google/cloud/language/artman_language_v1beta2.yaml generate go_gapic
artman> Final args:
artman>   api_name: language
artman>   api_version: v1beta2
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-language-go
artman>   gapic_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/v1beta2/language_gapic.yaml
artman>   generator_args: null
artman>   import_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   language: go
artman>   organization_name: google-cloud
artman>   output_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>   root_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   service_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/language_v1beta2.yaml
artman>   src_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/v1beta2
artman>   toolkit_path: /Users/deklerk/workspace/toolkit
artman>
artman> Running artman command in a Docker instance.
artman> artman> Final args:
artman>   api_name: language
artman>   api_version: v1beta2
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/gapi-cloud-language-go
artman>   gapic_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/v1beta2/language_gapic.yaml
artman>   generator_args: null
artman>   import_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   language: go
artman>   organization_name: google-cloud
artman>   output_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>   root_dir: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis
artman>   service_yaml: /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/language_v1beta2.yaml
artman>   src_proto_path:
artman>     - /Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/v1beta2
artman>   toolkit_path: /toolkit
artman>
artman> Creating GapicClientPipeline.
artman.output >
Missing input file.

artman> Traceback (most recent call last):
  File "/artman/artman/cli/main.py", line 71, in main
    engine.run()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 159, in run
    for _state in self.run_iter():
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 223, in run_iter
    failure.Failure.reraise_if_any(it)
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 292, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 299, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
    result = task.execute(**arguments)
  File "/artman/artman/tasks/protoc_tasks.py", line 57, in execute
    desc_protos)
  File "/artman/artman/tasks/task_base.py", line 64, in exec_command
    raise e
  File "/artman/artman/tasks/task_base.py", line 56, in exec_command
    output = subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['protoc', '--proto_path=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis', '--proto_path=/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/google/cloud/language/v1beta2', '--proto_path=/toolkit/build/toolpaths/protobufJavaDir', '--include_imports', '--include_source_info', '-o', '/Users/deklerk/workspace/go/src/github.com/googleapis/googleapis/artman-genfiles/google-cloud-language-v1beta2.desc']' returned non-zero exit status 1


artman> Artman execution failed. For additional logging, re-run the command with the "--verbose" flag
```

**Comment by jadekler** [comment]
(btw, I re-ran artman and it worked fine)

**Comment by andreamlin** [comment]
Ok, so it's protoc that's throwing this error.

**Comment by jadekler** [comment]
Sure? I'd believe that :) ¯\_(ツ)_/¯

**Comment by andreamlin** [comment]
Just noting that down that so that it would be written down somewhere. Also, https://github.com/protocolbuffers/protobuf/issues/3028

**Comment by hzyi-google** [comment]
We are not using artman for go generation any more.
