### ISSUE TITLE
module has no attribute FullLoader

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#733]
```
deklerk at deklerk in /tmp/googleapis on master*
$ /tmp/gocloud/regen-gapic.sh
++ dirname /tmp/gocloud/regen-gapic.sh
+ my_dir=/tmp/gocloud
+ source /tmp/gocloud/gapics.sh
++ APIS=(google/api/expr/artman_cel.yaml google/iam/artman_iam_admin.yaml google/cloud/asset/artman_cloudasset_v1beta1.yaml google/cloud/asset/artman_cloudasset_v1p2beta1.yaml google/cloud/asset/artman_cloudasset_v1.yaml google/iam/credentials/artman_iamcredentials_v1.yaml google/cloud/automl/artman_automl_v1beta1.yaml google/cloud/bigquery/datatransfer/artman_bigquerydatatransfer.yaml google/cloud/bigquery/storage/artman_bigquerystorage_v1beta1.yaml google/cloud/dataproc/artman_dataproc_v1.yaml google/cloud/dataproc/artman_dataproc_v1beta2.yaml google/cloud/dialogflow/artman_dialogflow_v2.yaml google/cloud/iot/artman_cloudiot.yaml google/cloud/irm/artman_irm_v1alpha2.yaml google/cloud/kms/artman_cloudkms.yaml google/cloud/language/artman_language_v1.yaml google/cloud/language/artman_language_v1beta2.yaml google/cloud/oslogin/artman_oslogin_v1.yaml google/cloud/oslogin/artman_oslogin_v1beta.yaml google/cloud/phishingprotection/artman_phishingprotection_v1beta1.yaml google/cloud/recaptchaenterprise/artman_recaptchaenterprise_v1beta1.yaml google/cloud/redis/artman_redis_v1beta1.yaml google/cloud/redis/artman_redis_v1.yaml google/cloud/scheduler/artman_cloudscheduler_v1beta1.yaml google/cloud/scheduler/artman_cloudscheduler_v1.yaml google/cloud/securitycenter/artman_securitycenter_v1beta1.yaml google/cloud/securitycenter/artman_securitycenter_v1.yaml google/cloud/speech/artman_speech_v1.yaml google/cloud/speech/artman_speech_v1p1beta1.yaml google/cloud/talent/artman_talent_v4beta1.yaml google/cloud/tasks/artman_cloudtasks_v2beta2.yaml google/cloud/tasks/artman_cloudtasks_v2beta3.yaml google/cloud/tasks/artman_cloudtasks_v2.yaml google/cloud/texttospeech/artman_texttospeech_v1.yaml google/cloud/videointelligence/artman_videointelligence_v1.yaml google/cloud/videointelligence/artman_videointelligence_v1beta1.yaml google/cloud/videointelligence/artman_videointelligence_v1beta2.yaml google/cloud/vision/artman_vision_v1.yaml google/cloud/vision/artman_vision_v1p1beta1.yaml google/cloud/webrisk/artman_webrisk_v1beta1.yaml google/devtools/artman_clouddebugger.yaml google/devtools/clouderrorreporting/artman_errorreporting.yaml google/devtools/cloudtrace/artman_cloudtrace_v1.yaml google/devtools/cloudtrace/artman_cloudtrace_v2.yaml google/devtools/containeranalysis/artman_containeranalysis_v1beta1.yaml google/firestore/artman_firestore.yaml google/firestore/admin/artman_firestore_v1.yaml google/logging/artman_logging.yaml google/longrunning/artman_longrunning.yaml google/monitoring/artman_monitoring.yaml google/privacy/dlp/artman_dlp_v2.yaml google/pubsub/artman_pubsub.yaml google/spanner/admin/database/artman_spanner_admin_database.yaml google/spanner/admin/instance/artman_spanner_admin_instance.yaml google/spanner/artman_spanner.yaml)
++ HAS_MANUAL=(errorreporting/apiv1beta1 firestore/apiv1beta1 firestore/apiv1 logging/apiv2 longrunning/autogen pubsub/apiv1 spanner/apiv1 trace/apiv1)
+ for api in "${APIS[@]}"
+ rm -rf 'artman-genfiles/*'
+ artman --config google/api/expr/artman_cel.yaml generate go_gapic
Traceback (most recent call last):
  File "/usr/local/google/home/deklerk/.local/bin/artman", line 10, in <module>
    sys.exit(main())
  File "/usr/local/google/home/deklerk/.local/lib/python2.7/site-packages/artman/cli/main.py", line 61, in main
    user_config = loader.read_user_config(flags.user_config)
  File "/usr/local/google/home/deklerk/.local/lib/python2.7/site-packages/artman/config/loader.py", line 99, in read_user_config
    json_string = json.dumps(yaml.load(f, Loader=yaml.FullLoader))
AttributeError: 'module' object has no attribute 'FullLoader'

```

Same problem when I install it with python3.

**Comment by alexander-fenster** [comment]
Looks like either Python 2.7 or some dependency problem. Suggested to use `virtualenv`:

```
virtualenv -p python3.7 artman-venv
. artman-venv/bin/activate
pip install googleapis-artman
```
