### ISSUE TITLE
mysterious error

### ISSUE THREAD

**Issue by jadekler** [googleapis/artman#761]
Anyone know what this is about? This happens after a bunch of other APIs generate successfully:

```
                                                               artman> artman> Final args:
artman>   api_name: monitoring
artman>   api_version: v3
artman>   artifact_type: GAPIC
artman>   aspect: ALL
artman>   gapic_code_dir: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/artman-genfiles/gapi-cloud-monitoring-go
artman>   gapic_yaml: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/v3/monitoring_gapic.yaml
artman>   generator_args: null
artman>   import_proto_path:
artman>     - /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis
artman>   language: go
artman>   organization_name: google-cloud
artman>   output_dir: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/artman-genfiles
artman>   proto_deps:
artman>     - name: google-common-protos
artman>   proto_package: ''
artman>   root_dir: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis
artman>   samples: ''
artman>   service_yaml: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/monitoring.yaml
artman>   src_proto_path:
artman>     - /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/v3
artman>   toolkit_path: /toolkit
artman>
artman> Creating GapicClientPipeline.
artman.output >
WARNING: toplevel: (lint) control-presence: Service monitoring.googleapis.com does not have control environment configured.
WARNING: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/monitoring.yaml:148: auth rule has selector(s) 'google.monitoring.v3.AgentTranslationService.CreateCollectdTimeSeries' that do not match and are not shadowed by other rules.
ERROR: toplevel: interface not reachable: google.monitoring.v3.ServiceMonitoringService.
WARNING: toplevel: (lint) control-presence: Service monitoring.googleapis.com does not have control environment configured.
WARNING: /private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/monitoring.yaml:148: auth rule has selector(s) 'google.monitoring.v3.AgentTranslationService.CreateCollectdTimeSeries' that do not match and are not shadowed by other rules.
ERROR: toplevel: interface not reachable: google.monitoring.v3.ServiceMonitoringService.

artman> Traceback (most recent call last):
  File "/artman/artman/cli/main.py", line 72, in main
    engine.run()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 247, in run
    for _state in self.run_iter(timeout=timeout):
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/engine.py", line 340, in run_iter
    failure.Failure.reraise_if_any(er_failures)
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 339, in reraise_if_any
    failures[0].reraise()
  File "/usr/local/lib/python3.5/dist-packages/taskflow/types/failure.py", line 346, in reraise
    six.reraise(*self._exc_info)
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/taskflow/engines/action_engine/executor.py", line 53, in _execute_task
    result = task.execute(**arguments)
  File "/artman/artman/tasks/gapic_tasks.py", line 148, in execute
    task_utils.gapic_gen_task(toolkit_path, [gapic_artifact] + args))
  File "/artman/artman/tasks/task_base.py", line 64, in exec_command
    raise e
  File "/artman/artman/tasks/task_base.py", line 56, in exec_command
    output = subprocess.check_output(args, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-cp', '/toolkit/build/libs/gapic-generator-latest-fatjar.jar', 'com.google.api.codegen.GeneratorMain', 'LEGACY_GAPIC_AND_PACKAGE', '--descriptor_set=/private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/artman-genfiles/google-cloud-monitoring-v3.desc', '--package_yaml2=/private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/artman-genfiles/go_google-cloud-monitoring-v3_package2.yaml', '--output=/private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/artman-genfiles/gapi-cloud-monitoring-go', '--language=go', '--service_yaml=/private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/monitoring.yaml', '--gapic_yaml=/private/var/folders/c2/cvxltzcd66v5lx14hm1j76q000h16k/T/update-genproto607930794/googleapis/google/monitoring/v3/monitoring_gapic.yaml']' returned non-zero exit status 1


artman> Artman execution failed. For additional logging, re-run the command with the "--verbose" flag
error generating gapics (may need to check logs for more errors): exit status 32
exit status 1
```

**Comment by jadekler** [comment]
Seems to have disappeared.
