### ISSUE TITLE
fix cel API generation

### ISSUE THREAD

**Issue by alexander-fenster** [googleapis/artman#775]
It currently fails.

https://github.com/googleapis/artman/blob/fcc5de85002c7a9d6c9bc9e46b313daef0aa7c03/test/smoketest_artman.py#L50

**Comment by jadekler** [comment]
```
go: downloading golang.org/x/text v0.3.0
go: extracting golang.org/x/text v0.3.0
go: finding golang.org/x/net v0.0.0-20190213061140-3a22650c66bd
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding golang.org/x/text v0.3.0
artman generating google/api/expr/artman_cel.yaml
Traceback (most recent call last):
  File "/usr/bin/artman", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (ply 3.11 (/usr/lib/python2.7/site-packages), Requirement.parse('ply==3.8'), set(['google-gax']))
error generating gapics (may need to check logs for more errors): exit status 1
exit status 1
```

**Comment by hzyi-google** [comment]
@alexander-fenster Is it still a problem?

**Comment by jadekler** [comment]
This was fixed. Sorry!

**Comment by hzyi-google** [comment]
Great. Thanks for the update!
